// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/chub-es/go-link-shortener/internal/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockLink is a mock of Link interface.
type MockLink struct {
	ctrl     *gomock.Controller
	recorder *MockLinkMockRecorder
}

// MockLinkMockRecorder is the mock recorder for MockLink.
type MockLinkMockRecorder struct {
	mock *MockLink
}

// NewMockLink creates a new mock instance.
func NewMockLink(ctrl *gomock.Controller) *MockLink {
	mock := &MockLink{ctrl: ctrl}
	mock.recorder = &MockLinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLink) EXPECT() *MockLinkMockRecorder {
	return m.recorder
}

// CreateLink mocks base method.
func (m *MockLink) CreateLink(c context.Context, l entity.Link) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLink", c, l)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLink indicates an expected call of CreateLink.
func (mr *MockLinkMockRecorder) CreateLink(c, l interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLink", reflect.TypeOf((*MockLink)(nil).CreateLink), c, l)
}

// SearchLink mocks base method.
func (m *MockLink) SearchLink(c context.Context, shortURL string) (entity.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchLink", c, shortURL)
	ret0, _ := ret[0].(entity.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchLink indicates an expected call of SearchLink.
func (mr *MockLinkMockRecorder) SearchLink(c, shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchLink", reflect.TypeOf((*MockLink)(nil).SearchLink), c, shortURL)
}

// MockLinkRepo is a mock of LinkRepo interface.
type MockLinkRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLinkRepoMockRecorder
}

// MockLinkRepoMockRecorder is the mock recorder for MockLinkRepo.
type MockLinkRepoMockRecorder struct {
	mock *MockLinkRepo
}

// NewMockLinkRepo creates a new mock instance.
func NewMockLinkRepo(ctrl *gomock.Controller) *MockLinkRepo {
	mock := &MockLinkRepo{ctrl: ctrl}
	mock.recorder = &MockLinkRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkRepo) EXPECT() *MockLinkRepoMockRecorder {
	return m.recorder
}

// FindOne mocks base method.
func (m *MockLinkRepo) FindOne(c context.Context, columns string, args ...interface{}) (entity.Link, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{c, columns}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(entity.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockLinkRepoMockRecorder) FindOne(c, columns interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{c, columns}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockLinkRepo)(nil).FindOne), varargs...)
}

// Insert mocks base method.
func (m *MockLinkRepo) Insert(c context.Context, link entity.Link) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", c, link)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockLinkRepoMockRecorder) Insert(c, link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockLinkRepo)(nil).Insert), c, link)
}

// UpShowned mocks base method.
func (m *MockLinkRepo) UpShowned(c context.Context, linkID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpShowned", c, linkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpShowned indicates an expected call of UpShowned.
func (mr *MockLinkRepoMockRecorder) UpShowned(c, linkID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpShowned", reflect.TypeOf((*MockLinkRepo)(nil).UpShowned), c, linkID)
}
